# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-05 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChoiceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.IntegerField(help_text='题库唯一标识', verbose_name='题库id')),
                ('question', models.CharField(blank=True, help_text='题目', max_length=255, null=True, verbose_name='问题')),
                ('answer', models.IntegerField(blank=True, help_text='答案', null=True, verbose_name='答案')),
                ('item1', models.CharField(blank=True, help_text='选项一', max_length=255, null=True, verbose_name='选项1')),
                ('item2', models.CharField(blank=True, help_text='选项二', max_length=255, null=True, verbose_name='选项2')),
                ('item3', models.CharField(blank=True, help_text='选项三', max_length=255, null=True, verbose_name='选项3')),
                ('item4', models.CharField(blank=True, help_text='选项四', max_length=255, null=True, verbose_name='选项4')),
            ],
        ),
    ]
